2020-03-15 22:37:16 - TRACE    | T MAIN Totally detailed message [main.py:main:164]
2020-03-15 22:37:16 - INFO     | E MAIN Log level: 0 [main.py:main:165]
2020-03-15 22:37:16 - INFO     | W Adding 2+3=5 [main.py:add:132]
2020-03-15 22:37:16 - DEBUG    | D MAIN add_result: 5 [main.py:main:168]
2020-03-15 22:37:16 - DEBUG    | D UTILS Multiplying 2*3=6 [utils.py:multiply:6]
2020-03-15 22:37:16 - INFO     | I UTILS Multiplying 2*3=6 [utils.py:multiply:7]
2020-03-15 22:37:16 - WARNING  | W UTILS Multiplying 2*3=6 [utils.py:multiply:8]
2020-03-15 22:37:16 - ERROR    | E UTILS Multiplying 2*3=6 [utils.py:multiply:9]
2020-03-15 22:37:16 - CRITICAL | C UTILS Multiplying 2*3=6 [utils.py:multiply:10]
2020-03-15 22:37:16 - SUCCESS  | S UTILS Multiplying 2*3=6 [utils.py:multiply:11]
2020-03-15 22:37:16 - INFO     | I MAIN multiply_result: 6 [main.py:main:171]
2020-03-15 22:37:16 - SUCCESS  | S MAIN Successful message [main.py:main:173]
2020-03-15 22:37:16 - OK       | O MAIN This opration was [32m[1m[ OK ][0m [main.py:main:174]
