2020-03-15 22:22:49 - ERROR    | E UTILS Multiplying 2*3=6 [utils.py:multiply:9]
2020-03-15 22:22:49 - CRITICAL | C UTILS Multiplying 2*3=6 [utils.py:multiply:10]
2020-03-15 22:22:49 - SUCCESS  | S UTILS Multiplying 2*3=6 [utils.py:multiply:11]
2020-03-15 22:22:49 - INFO     | I MAIN multiply_result: 6 [main.py:main:161]
2020-03-15 22:22:49 - SUCCESS  | S MAIN Successful message [main.py:main:163]
2020-03-15 22:22:49 - OK       | O MAIN This opration was [32m[1m[ OK ][0m [main.py:main:164]
2020-03-15 22:22:51 - TRACE    | T MAIN Totally detailed message [main.py:main:154]
2020-03-15 22:22:51 - INFO     | E MAIN Log level: 0 [main.py:main:155]
2020-03-15 22:22:51 - INFO     | W Adding 2+3=5 [main.py:add:122]
2020-03-15 22:22:51 - DEBUG    | D MAIN add_result: 5 [main.py:main:158]
2020-03-15 22:22:51 - DEBUG    | D UTILS Multiplying 2*3=6 [utils.py:multiply:6]
2020-03-15 22:22:51 - INFO     | I UTILS Multiplying 2*3=6 [utils.py:multiply:7]
